version: '3.9'
services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sensors
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mysql:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sensors
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  mssql:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: mssql-db
    environment:
      SA_PASSWORD: StrongPassword123!
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

  api:
    build:
      context: .
      dockerfile: ./EnersoftSensorsManagementSystem.API/Dockerfile
    container_name: api
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      POSTGRES_CONNECTION: "Host=postgres-db;Port=5432;Database=sensors;Username=postgres;Password=postgres"
      MYSQL_CONNECTION: "Server=mysql-db;Port=3306;Database=sensors;User=root;Password=root"
      MSSQL_CONNECTION: "Server=mssql-db,1433;Database=sensors;User Id=sa;Password=StrongPassword123!"
      DB_TYPE: "Postgres"
    depends_on:
      - postgres
      - mysql
      - mssql

volumes:
  postgres_data:
  mysql_data:
  mssql_data:
